name: Deploy Example Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Pub get (root package)
        run: flutter pub get

      - name: Pub get (example app)
        working-directory: example
        run: flutter pub get

      - name: Enable web
        run: flutter config --enable-web

      - name: Build Flutter Web (example)
        working-directory: example
        run: flutter build web --release

      - name: Upload web build as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: example/build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
